input {
  tcp {
    port => 514
    type => syslog
    codec => cef {
      # delimiter => "\n"
      ecs_compatibility => disabled
    }
  }
  udp {
    port => 514
    type => syslog
    codec => cef {
      # delimiter => "\n"
      ecs_compatibility => disabled
    }
  }
}
filter {
  if ([destinationPort]=="2379") { # Kubernetes
    drop {
    }
  }
}


output {
  pipeline {
    send_to => ["sentinel"]
  }
}

