input {
    pipeline {
        address => "sentinel"
    }
}
filter {
    mutate {
        add_tag => [ "<environment_name>" ]
    }
  
 
}
output {
    microsoft-sentinel-log-analytics-logstash-output-plugin {
        client_app_Id => "<appId>"
        client_app_secret => "<appSecret>"
        tenant_id => "<tenantId>"
        data_collection_endpoint => "<dce>"
        dcr_immutable_id => "<dcrId>"
        dcr_stream_name => "<table>"
    }
}
